// Dummy bus results
export const buses = [
  {
    id: 1,
    operator: "Shyamoli Paribahan",
    route: "Dhaka → Chittagong",
    departure: "01:00 PM",
    departureDate: "Wed, 1 Oct",
    departureCity: "Dhaka",
    arrival: "09:00 PM",
    arrivalDate: "Wed, 1 Oct",
    arrivalCity: "Chittagong",
    duration: "8h 0m",
    price: 900,
    discount: 100,
    seats: 15,
  },
  {
    id: 2,
    operator: "Shyamoli Paribahan",
    route: "Dhaka → Chittagong",
    departure: "11:15 PM",
    departureDate: "Wed, 1 Oct",
    departureCity: "Dhaka",
    arrival: "07:15 AM",
    arrivalDate: "Thu, 2 Oct",
    arrivalCity: "Chittagong",
    duration: "8h 0m",
    price: 900,
    discount: 100,
    seats: 18,
  },
  {
    id: 3,
    operator: "Evergreen Transport Ltd",
    route: "Dhaka → Cox’s Bazar",
    departure: "08:45 PM",
    departureDate: "Wed, 1 Oct",
    departureCity: "Dhaka",
    arrival: "02:00 AM",
    arrivalDate: "Thu, 2 Oct",
    arrivalCity: "Cox’s Bazar",
    duration: "5h 15m",
    price: 1000,
    discount: 0,
    seats: 31,
  },
  {
    id: 4,
    operator: "Shyamoli Paribahan",
    route: "Dhaka → Chittagong",
    departure: "01:00 PM",
    departureDate: "Wed, 1 Oct",
    departureCity: "Dhaka",
    arrival: "09:00 PM",
    arrivalDate: "Wed, 1 Oct",
    arrivalCity: "Chittagong",
    duration: "8h 0m",
    price: 900,
    discount: 100,
    seats: 15,
  },
  {
    id: 5,
    operator: "Shyamoli Paribahan",
    route: "Dhaka → Chittagong",
    departure: "11:15 PM",
    departureDate: "Wed, 1 Oct",
    departureCity: "Dhaka",
    arrival: "07:15 AM",
    arrivalDate: "Thu, 2 Oct",
    arrivalCity: "Chittagong",
    duration: "8h 0m",
    price: 900,
    discount: 100,
    seats: 18,
  },
  {
    id: 6,
    operator: "Evergreen Transport Ltd",
    route: "Dhaka → Cox’s Bazar",
    departure: "08:45 PM",
    departureDate: "Wed, 1 Oct",
    departureCity: "Dhaka",
    arrival: "02:00 AM",
    arrivalDate: "Thu, 2 Oct",
    arrivalCity: "Cox’s Bazar",
    duration: "5h 15m",
    price: 1000,
    discount: 0,
    seats: 31,
  },
];
// Example options (dummy data from Bangladesh)
export const operators = [
  "Shyamoli Paribahan",
  "Hanif Enterprise",
  "Green Line",
  "Shohag Elite",
];
export const boardingPoints = ["Gabtoli", "Mohakhali", "Sayedabad", "Uttara"];
export const droppingPoints = ["Chittagong", "Cox’s Bazar", "Sylhet", "Khulna"];